"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[390],{96390:function(__unused_webpack_module,__webpack_exports__,__webpack_require__){eval(`__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": function() { return /* binding */ EmptyRoute; }
/* harmony export */ });
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(67294);
/* harmony import */ var umi__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(71551);
/* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(85893);
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!



function EmptyRoute() {
  var context = (0,umi__WEBPACK_IMPORTED_MODULE_1__.useOutletContext)();
  return /*#__PURE__*/(0,react_jsx_runtime__WEBPACK_IMPORTED_MODULE_2__.jsx)(umi__WEBPACK_IMPORTED_MODULE_1__.Outlet, {
    context: context
  });
}//# sourceURL=[module]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiOTYzOTAuanMiLCJtYXBwaW5ncyI6Ijs7Ozs7OztBQUFBO0FBQ0E7QUFDQTtBQUMwQjtBQUNxQjtBQUFBO0FBQ2hDLFNBQVNLLFVBQVVBLENBQUEsRUFBRztFQUNuQyxJQUFNQyxPQUFPLEdBQUdKLHFEQUFnQixDQUFDLENBQUM7RUFDbEMsb0JBQU9FLHNEQUFBLENBQUNILHVDQUFNO0lBQUNLLE9BQU8sRUFBRUE7RUFBUSxDQUFFLENBQUM7QUFDckMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvLnVtaS1wcm9kdWN0aW9uL2NvcmUvRW1wdHlSb3V0ZS50c3g/YjRkOSJdLCJzb3VyY2VzQ29udGVudCI6WyIvLyBAdHMtbm9jaGVja1xuLy8gVGhpcyBmaWxlIGlzIGdlbmVyYXRlZCBieSBVbWkgYXV0b21hdGljYWxseVxuLy8gRE8gTk9UIENIQU5HRSBJVCBNQU5VQUxMWSFcbmltcG9ydCBSZWFjdCBmcm9tICdyZWFjdCc7XG5pbXBvcnQgeyBPdXRsZXQsIHVzZU91dGxldENvbnRleHQgfSBmcm9tICd1bWknO1xuZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gRW1wdHlSb3V0ZSgpIHtcbiAgY29uc3QgY29udGV4dCA9IHVzZU91dGxldENvbnRleHQoKTtcbiAgcmV0dXJuIDxPdXRsZXQgY29udGV4dD17Y29udGV4dH0gLz47XG59XG4iXSwibmFtZXMiOlsiUmVhY3QiLCJPdXRsZXQiLCJ1c2VPdXRsZXRDb250ZXh0IiwianN4IiwiX2pzeCIsIkVtcHR5Um91dGUiLCJjb250ZXh0Il0sInNvdXJjZVJvb3QiOiIifQ==
//# sourceURL=webpack-internal:///96390
`)}}]);
